
name: "contentFlow"

on:
  push:
    branches:
      - main
    paths:
      - content/**

jobs:
  mainPush:
    name: "content"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_ARN }} # ここにGitHub Secretsに保存した変数名が入ります。
        aws-region: ap-northeast-1
    
    - name: Set current datetime as env variable
      env:
        TZ: 'Asia/Tokyo' # タイムゾーン指定
      run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Push to CodeCommit (Content)
      run: |
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true
        git remote add codecommit https://git-codecommit.${{ env.AWS_REGION }}.amazonaws.com/v1/repos/change-branch-test
        git checkout -b content
        echo ${{ env.CURRENT_DATETIME }} > time_log.txt
        git add time_log.txt
        git commit -m "time_log add"
        git push codecommit content

        

