
name: "TestWorkFlow"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mainPush:
    name: "sample"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.IAM_ROLE_ARN }} # ここにGitHub Secretsに保存した変数名が入ります。
        aws-region: ap-northeast-1
    - name: Push to CodeCommit (Mirroring)
      run: |
        git checkout -b hoge
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true
        git remote add codecommit https://git-codecommit.${{ env.AWS_REGION }}.amazonaws.com/v1/repos/change-branch-test
        git push --mirror codecommit

    - name: Echo Branch
      run: |
        git checkout 

