
name: "TestWorkFlow"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mainPush:
    name: "sample"
    steps:
    - name: Echo Branch
      run: |
        pwd
        ls -a
        cd ..
        pwd
        mkidr test
        ls
