
name: "TestWorkFlow"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mainPush:
    name: "TestWorkFLow Echo"
    runs-on: ubuntu-latest
    steps:
    - name: Echo Branch
      run: |
        pwd
        ls
        cd ..
        pwd
        ls