
name: "TestWorkFlow"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mainPush:
    name: "sample"
    runs-on: ubuntu-latest
    steps:
    - name: Echo Branch
      run: |
        pwd
        ls -a
        cd ..
        pwd
        mkdir test
        echo "${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}"

