
name: "TestWorkFlow"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mainPush:
    name: "sample"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Echo Branch
      run: |
        cd ..
        echo "--------------------"
        mkdir test
        echo "${GITHUB_REPOSITORY_OWNER}"
        echo "--------------------"
        ls

